const REFERENCE_SEAT_FINDER_NAME = "seatFinder";
const REFERENCE_CURRENT_SESSION_NAME = "session";
const REFERENCE_STATE_CHANGES_NAME = "stateChanges";
const REFERENCE_HISTORY_NAME = "history";
const REFERENCE_SESSION_HAS_FAILURE_NAME = "hasFailure";
const REFERENCE_TIMER_NAME = "timer";


export {
    REFERENCE_SEAT_FINDER_NAME,
    REFERENCE_CURRENT_SESSION_NAME,
    REFERENCE_SESSION_HAS_FAILURE_NAME,
    REFERENCE_STATE_CHANGES_NAME,
    REFERENCE_HISTORY_NAME,
    REFERENCE_TIMER_NAME,
};
