export enum RequestType {
    ReserveSeat,
    CancelReservation,
    OccupySeat,
    StopUsingSeat,
    DoBusiness,
    FinishBusiness,
    ShiftToBusiness,
    LeaveAway,
    ResumeUsing,
    ChangeCurrentTimeoutTime,
    ChangeUsageTimeoutTime,
    Block,
    Unblock,
    NoOp,
}
