[versions]
androidxAppCompat = "1.5.1"
androidxCore = "1.9.0"
androidxEspresso = "3.5.0"
androidxTestExt = "1.1.5"
junit4 = "4.13.2"


[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspresso" }
androidx-test-ext = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestExt" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }