const COLLECTION_GROUP_STORE_NAME = "stores";
const COLLECTION_GROUP_SECTION_NAME = "sections";
const COLLECTION_GROUP_SEAT_NAME = "seats";


const DOCUMENT_TOTAL_SECTIONS_NAME = "totalSections";
const DOCUMENT_TOTAL_AVAILABLE_SEATS_NAME = "totalAvailableSeats";
const DOCUMENT_TOTAL_SEATS_NAME = "totalSeats";

export {
    COLLECTION_GROUP_STORE_NAME,
    COLLECTION_GROUP_SECTION_NAME,
    COLLECTION_GROUP_SEAT_NAME,
    DOCUMENT_TOTAL_SECTIONS_NAME,
    DOCUMENT_TOTAL_AVAILABLE_SEATS_NAME,
    DOCUMENT_TOTAL_SEATS_NAME,
};

