const COLLECTION_GROUP_STORE_NAME = "stores";
const COLLECTION_GROUP_SECTION_NAME = "sections";
const COLLECTION_GROUP_SEAT_NAME = "seats";


export {
    COLLECTION_GROUP_STORE_NAME,
    COLLECTION_GROUP_SECTION_NAME,
    COLLECTION_GROUP_SEAT_NAME,
};

